CREATE TABLE "BHUB_PRODUCT_OPTION" (
	"PRODUCT_OPTION_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"PRODUCT_ID"	VARCHAR2(30)		NOT NULL,
	"OPTION_ID"	VARCHAR2(30)		NOT NULL,
	"DISPLAY_OPTION_NM"	VARCHAR2(100)		NULL,
	"SORT_SEQ"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_PRODUCT_OPTION"."PRODUCT_OPTION_ID" IS '상품옵션ID';

COMMENT ON COLUMN "BHUB_PRODUCT_OPTION"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_PRODUCT_OPTION"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "BHUB_PRODUCT_OPTION"."OPTION_ID" IS '옵션ID';

COMMENT ON COLUMN "BHUB_PRODUCT_OPTION"."DISPLAY_OPTION_NM" IS '표시옵션명';

COMMENT ON COLUMN "BHUB_PRODUCT_OPTION"."SORT_SEQ" IS '정렬순서';

COMMENT ON COLUMN "BHUB_PRODUCT_OPTION"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_PRODUCT_OPTION"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_PRODUCT_OPTION"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_PRODUCT_OPTION"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_PRODUCT_OPTION"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_CHANNEL_POLICY_VALUE" (
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"CHANNEL_CD"	VARCHAR2(20)		NOT NULL,
	"POLICY_CD"	VARCHAR2(50)		NOT NULL,
	"POLICY_VALUE"	VARCHAR2(4000)		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY_VALUE"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY_VALUE"."CHANNEL_CD" IS '채널코드';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY_VALUE"."POLICY_CD" IS '정책코드';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY_VALUE"."POLICY_VALUE" IS '회사별';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY_VALUE"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY_VALUE"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY_VALUE"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY_VALUE"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY_VALUE"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY_VALUE"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_CATEGORY" (
	"CATEGORY_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"PR_CATEGORY_ID"	VARCHAR2(30)		NULL,
	"CATEGORY_CD"	VARCHAR2(30)		NOT NULL,
	"CATEGORY_NM"	VARCHAR2(200)		NOT NULL,
	"CATEGORY_LVL"	NUMBER(5,0)	DEFAULT 1	NOT NULL,
	"LEAF_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"SORT_SEQ"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_CATEGORY"."CATEGORY_ID" IS '카테고리ID';

COMMENT ON COLUMN "BHUB_CATEGORY"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_CATEGORY"."PR_CATEGORY_ID" IS '상위카테고리ID';

COMMENT ON COLUMN "BHUB_CATEGORY"."CATEGORY_CD" IS '카테고리코드';

COMMENT ON COLUMN "BHUB_CATEGORY"."CATEGORY_NM" IS '카테고리명';

COMMENT ON COLUMN "BHUB_CATEGORY"."CATEGORY_LVL" IS '카테고리레벨';

COMMENT ON COLUMN "BHUB_CATEGORY"."LEAF_YN" IS '최하위여부';

COMMENT ON COLUMN "BHUB_CATEGORY"."SORT_SEQ" IS '정렬순서';

COMMENT ON COLUMN "BHUB_CATEGORY"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_CATEGORY"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_CATEGORY"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_CATEGORY"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_CATEGORY"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_CATEGORY"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_ORDER" (
	"ORDER_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"CHANNEL_CD"	VARCHAR2(20)		NOT NULL,
	"CHANNEL_ACCOUNT_ID"	VARCHAR2(30)		NOT NULL,
	"CHANNEL_ORDER_ID"	VARCHAR2(100)		NOT NULL,
	"ORDER_NO"	VARCHAR2(50)		NULL,
	"ORDER_DT"	DATE		NULL,
	"PAY_DT"	DATE		NULL,
	"ORDER_STATUS_CD"	VARCHAR2(20)		NULL,
	"ORDER_AMT"	NUMBER(18,0)		NULL,
	"PAY_AMT"	NUMBER(18,0)		NULL,
	"BUYER_NM"	VARCHAR2(100)		NULL,
	"BUYER_TEL"	VARCHAR2(50)		NULL,
	"RECEIVER_NM"	VARCHAR2(100)		NULL,
	"RECEIVER_TEL"	VARCHAR2(50)		NULL,
	"RECEIVER_ADDR1"	VARCHAR2(300)		NULL,
	"RECEIVER_ADDR2"	VARCHAR2(300)		NULL,
	"DELV_MSG"	VARCHAR2(400)		NULL,
	"ERP_IF_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"ERP_IF_DT"	DATE		NULL,
	"ERP_IF_MSG"	VARCHAR2(1000)		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_ORDER"."ORDER_ID" IS '주문ID';

COMMENT ON COLUMN "BHUB_ORDER"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_ORDER"."CHANNEL_CD" IS '채널코드';

COMMENT ON COLUMN "BHUB_ORDER"."CHANNEL_ACCOUNT_ID" IS '채널계정ID';

COMMENT ON COLUMN "BHUB_ORDER"."CHANNEL_ORDER_ID" IS '채널주문번호';

COMMENT ON COLUMN "BHUB_ORDER"."ORDER_NO" IS '허브주문번호';

COMMENT ON COLUMN "BHUB_ORDER"."ORDER_DT" IS '주문일시';

COMMENT ON COLUMN "BHUB_ORDER"."PAY_DT" IS '결제일시';

COMMENT ON COLUMN "BHUB_ORDER"."ORDER_STATUS_CD" IS '주문상태코드';

COMMENT ON COLUMN "BHUB_ORDER"."ORDER_AMT" IS '주문금액';

COMMENT ON COLUMN "BHUB_ORDER"."PAY_AMT" IS '결제금액';

COMMENT ON COLUMN "BHUB_ORDER"."BUYER_NM" IS '주문자명';

COMMENT ON COLUMN "BHUB_ORDER"."BUYER_TEL" IS '주문자연락처';

COMMENT ON COLUMN "BHUB_ORDER"."RECEIVER_NM" IS '수령자명';

COMMENT ON COLUMN "BHUB_ORDER"."RECEIVER_TEL" IS '수령자연락처';

COMMENT ON COLUMN "BHUB_ORDER"."RECEIVER_ADDR1" IS '수령자주소1';

COMMENT ON COLUMN "BHUB_ORDER"."RECEIVER_ADDR2" IS '수령자주소2';

COMMENT ON COLUMN "BHUB_ORDER"."DELV_MSG" IS '배송메시지';

COMMENT ON COLUMN "BHUB_ORDER"."ERP_IF_YN" IS 'ERP전송여부';

COMMENT ON COLUMN "BHUB_ORDER"."ERP_IF_DT" IS 'ERP전송일시';

COMMENT ON COLUMN "BHUB_ORDER"."ERP_IF_MSG" IS 'ERP전송메시지';

COMMENT ON COLUMN "BHUB_ORDER"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_ORDER"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_ORDER"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_ORDER"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_ORDER"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_ORDER"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_PRODUCT_PRICE" (
	"PRICE_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"PRODUCT_ID"	VARCHAR2(30)		NOT NULL,
	"ITEM_ID"	VARCHAR2(30)		NULL,
	"PRICE_TP"	VARCHAR2(20)		NOT NULL,
	"START_DT"	DATE		NULL,
	"END_DT"	DATE		NULL,
	"SALE_PRC_AMT"	NUMBER(18,0)		NULL,
	"PUR_PRC_AMT"	NUMBER(18,0)		NULL,
	"CONSUMER_PRC_AMT"	NUMBER(18,0)		NULL,
	"DISCOUNT_AMT"	NUMBER(18,0)		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_PRODUCT_PRICE"."PRICE_ID" IS '가격ID';

COMMENT ON COLUMN "BHUB_PRODUCT_PRICE"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_PRODUCT_PRICE"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "BHUB_PRODUCT_PRICE"."ITEM_ID" IS 'ITEM';

COMMENT ON COLUMN "BHUB_PRODUCT_PRICE"."PRICE_TP" IS '가격유형';

COMMENT ON COLUMN "BHUB_PRODUCT_PRICE"."START_DT" IS '적용시작일시';

COMMENT ON COLUMN "BHUB_PRODUCT_PRICE"."END_DT" IS '적용종료일시';

COMMENT ON COLUMN "BHUB_PRODUCT_PRICE"."SALE_PRC_AMT" IS '판매가';

COMMENT ON COLUMN "BHUB_PRODUCT_PRICE"."PUR_PRC_AMT" IS '구매가';

COMMENT ON COLUMN "BHUB_PRODUCT_PRICE"."CONSUMER_PRC_AMT" IS '소비자가';

COMMENT ON COLUMN "BHUB_PRODUCT_PRICE"."DISCOUNT_AMT" IS '할인금액';

COMMENT ON COLUMN "BHUB_PRODUCT_PRICE"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_PRODUCT_PRICE"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_PRODUCT_PRICE"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_PRODUCT_PRICE"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_PRODUCT_PRICE"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_PRODUCT_PRICE"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_RAW_BATCH" (
	"BATCH_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"CHANNEL_ACCOUNT_ID"	VARCHAR2(30)		NOT NULL,
	"COLLECT_TP"	VARCHAR2(20)		NOT NULL,
	"TARGET_TP"	VARCHAR2(20)		NOT NULL,
	"REQUEST_DT"	DATE		NULL,
	"START_DT"	DATE		NULL,
	"END_DT"	DATE		NULL,
	"STATUS_CD"	VARCHAR2(20)		NOT NULL,
	"TOTAL_CNT"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"SUCCESS_CNT"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"FAIL_CNT"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"DUP_CNT"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"SKIP_CNT"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"REQUEST_JSON"	CLOB		NULL,
	"RESULT_MSG"	VARCHAR2(2000)		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_RAW_BATCH"."BATCH_ID" IS '수집배치ID';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."CHANNEL_ACCOUNT_ID" IS '채널계정ID';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."COLLECT_TP" IS '수집유형';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."TARGET_TP" IS '대상유형(PRODUCT/ITEM/ORDER)';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."REQUEST_DT" IS '수집요청일시';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."START_DT" IS '수집시작일시';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."END_DT" IS '수집종료일시';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."STATUS_CD" IS '배치상태코드';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."TOTAL_CNT" IS '총대상건수';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."SUCCESS_CNT" IS '성공건수';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."FAIL_CNT" IS '실패건수';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."DUP_CNT" IS '중복건수';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."SKIP_CNT" IS '건너뜀건수';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."REQUEST_JSON" IS '요청JSON';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."RESULT_MSG" IS '결과메시지';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_RAW_BATCH"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_ITEM_OPTION" (
	"ITEM_OPTION_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"ITEM_ID"	VARCHAR2(30)		NOT NULL,
	"OPTION_ID"	VARCHAR2(30)		NOT NULL,
	"OPTION_VALUE_ID"	VARCHAR2(30)		NOT NULL,
	"OPTION_NM"	VARCHAR2(100)		NULL,
	"OPTION_VALUE_NM"	VARCHAR2(100)		NULL,
	"SORT_SEQ"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_ITEM_OPTION"."ITEM_OPTION_ID" IS 'ITEM옵션ID';

COMMENT ON COLUMN "BHUB_ITEM_OPTION"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_ITEM_OPTION"."ITEM_ID" IS 'ITEM';

COMMENT ON COLUMN "BHUB_ITEM_OPTION"."OPTION_ID" IS '옵션ID';

COMMENT ON COLUMN "BHUB_ITEM_OPTION"."OPTION_VALUE_ID" IS '옵션값ID';

COMMENT ON COLUMN "BHUB_ITEM_OPTION"."OPTION_NM" IS '옵션명';

COMMENT ON COLUMN "BHUB_ITEM_OPTION"."OPTION_VALUE_NM" IS '옵션값명';

COMMENT ON COLUMN "BHUB_ITEM_OPTION"."SORT_SEQ" IS '정렬순서';

COMMENT ON COLUMN "BHUB_ITEM_OPTION"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_ITEM_OPTION"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_ITEM_OPTION"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_ITEM_OPTION"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_ITEM_OPTION"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_ITEM_ERP_MAP" (
	"MAP_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"ITEM_ID"	VARCHAR2(30)		NOT NULL,
	"ERP_ITEM_CD"	VARCHAR2(30)		NOT NULL,
	"PRIMARY_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"SYNC_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"SYNC_DT"	DATE		NULL,
	"SYNC_MSG"	VARCHAR2(1000)		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_ITEM_ERP_MAP"."MAP_ID" IS '매핑ID';

COMMENT ON COLUMN "BHUB_ITEM_ERP_MAP"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_ITEM_ERP_MAP"."ITEM_ID" IS 'ITEM';

COMMENT ON COLUMN "BHUB_ITEM_ERP_MAP"."ERP_ITEM_CD" IS 'ERP';

COMMENT ON COLUMN "BHUB_ITEM_ERP_MAP"."PRIMARY_YN" IS '대표매핑여부';

COMMENT ON COLUMN "BHUB_ITEM_ERP_MAP"."SYNC_YN" IS '동기화여부';

COMMENT ON COLUMN "BHUB_ITEM_ERP_MAP"."SYNC_DT" IS '동기화일시';

COMMENT ON COLUMN "BHUB_ITEM_ERP_MAP"."SYNC_MSG" IS '동기화메시지';

COMMENT ON COLUMN "BHUB_ITEM_ERP_MAP"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_ITEM_ERP_MAP"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_ITEM_ERP_MAP"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_ITEM_ERP_MAP"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_ITEM_ERP_MAP"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_PRODUCT_ATTR" (
	"ATTR_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"PRODUCT_ID"	VARCHAR2(30)		NOT NULL,
	"ITEM_ID"	VARCHAR2(30)		NULL,
	"ATTR_KEY"	VARCHAR2(100)		NOT NULL,
	"ATTR_NM"	VARCHAR2(200)		NULL,
	"ATTR_VALUE"	VARCHAR2(4000)		NULL,
	"ATTR_TP"	VARCHAR2(20)		NULL,
	"REQUIRED_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"SORT_SEQ"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_PRODUCT_ATTR"."ATTR_ID" IS '속성ID';

COMMENT ON COLUMN "BHUB_PRODUCT_ATTR"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_PRODUCT_ATTR"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "BHUB_PRODUCT_ATTR"."ITEM_ID" IS 'ITEM';

COMMENT ON COLUMN "BHUB_PRODUCT_ATTR"."ATTR_KEY" IS '속성키';

COMMENT ON COLUMN "BHUB_PRODUCT_ATTR"."ATTR_NM" IS '속성명';

COMMENT ON COLUMN "BHUB_PRODUCT_ATTR"."ATTR_VALUE" IS '속성값';

COMMENT ON COLUMN "BHUB_PRODUCT_ATTR"."ATTR_TP" IS '속성유형';

COMMENT ON COLUMN "BHUB_PRODUCT_ATTR"."REQUIRED_YN" IS '필수여부';

COMMENT ON COLUMN "BHUB_PRODUCT_ATTR"."SORT_SEQ" IS '정렬순서';

COMMENT ON COLUMN "BHUB_PRODUCT_ATTR"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_PRODUCT_ATTR"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_PRODUCT_ATTR"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_PRODUCT_ATTR"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_PRODUCT_ATTR"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_PRODUCT_ATTR"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_MAPPING_REVIEW" (
	"REVIEW_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"REVIEW_TP"	VARCHAR2(20)		NOT NULL,
	"RAW_PRODUCT_ID"	VARCHAR2(30)		NULL,
	"RAWITEM_ID"	VARCHAR2(30)		NULL,
	"STATUS_CD"	VARCHAR2(20)		NOT NULL,
	"REQUEST_USER_ID"	VARCHAR2(20)		NULL,
	"REQUEST_DATETIME"	DATE		NULL,
	"REVIEW_USER_ID"	VARCHAR2(20)		NULL,
	"REVIEW_DATETIME"	DATE		NULL,
	"RESULT_CD"	VARCHAR2(20)		NULL,
	"RESULT_MSG"	VARCHAR2(2000)		NULL,
	"TARGET_PRODUCT_ID"	VARCHAR2(30)		NULL,
	"TARGETITEM_ID"	VARCHAR2(30)		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."REVIEW_ID" IS '검수ID';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."REVIEW_TP" IS '검수유형(PRODUCT/ITEM)';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."RAW_PRODUCT_ID" IS '원본상품ID';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."RAWITEM_ID" IS '원본ITEM';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."STATUS_CD" IS '검수상태코드';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."REQUEST_USER_ID" IS '검수요청자';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."REQUEST_DATETIME" IS '검수요청일시';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."REVIEW_USER_ID" IS '검수자';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."REVIEW_DATETIME" IS '검수일시';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."RESULT_CD" IS '검수결과코드';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."RESULT_MSG" IS '검수결과메시지';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."TARGET_PRODUCT_ID" IS '선정상품ID';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."TARGETITEM_ID" IS '선정ITEM';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_MAPPING_REVIEW"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_CHANNEL_SYNC_HIST" (
	"SYNC_HIST_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"CHANNEL_ACCOUNT_ID"	VARCHAR2(30)		NOT NULL,
	"SYNC_TP"	VARCHAR2(20)		NOT NULL,
	"TARGET_ID"	VARCHAR2(100)		NULL,
	"REQUEST_DT"	DATE		NULL,
	"START_DT"	DATE		NULL,
	"END_DT"	DATE		NULL,
	"STATUS_CD"	VARCHAR2(20)		NOT NULL,
	"SUCCESS_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"RESULT_CD"	VARCHAR2(50)		NULL,
	"RESULT_MSG"	VARCHAR2(2000)		NULL,
	"REQUEST_JSON"	CLOB		NULL,
	"RESPONSE_JSON"	CLOB		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."SYNC_HIST_ID" IS '동기화이력ID';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."CHANNEL_ACCOUNT_ID" IS '채널계정ID';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."SYNC_TP" IS '동기화유형(PRODUCT/ORDER/STOCK/PRICE/CATEGORY)';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."TARGET_ID" IS '대상ID';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."REQUEST_DT" IS '동기화요청일시';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."START_DT" IS '동기화시작일시';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."END_DT" IS '동기화종료일시';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."STATUS_CD" IS '동기화상태코드';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."SUCCESS_YN" IS '성공여부';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."RESULT_CD" IS '결과코드';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."RESULT_MSG" IS '결과메시지';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."REQUEST_JSON" IS '요청JSON';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."RESPONSE_JSON" IS '응답JSON';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_CHANNEL_SYNC_HIST"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_CHANNEL_CATEGORY" (
	"CHANNEL_CATEGORY_ID"	VARCHAR2(30)		NOT NULL,
	"CHANNEL_CD"	VARCHAR2(20)		NOT NULL,
	"PR_CATEGORY_ID"	VARCHAR2(30)		NULL,
	"CATEGORY_CD"	VARCHAR2(100)		NOT NULL,
	"CATEGORY_NM"	VARCHAR2(300)		NOT NULL,
	"CATEGORY_PATH"	VARCHAR2(1000)		NULL,
	"CATEGORY_LVL"	NUMBER(5,0)	DEFAULT 1	NOT NULL,
	"LEAF_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"SORT_SEQ"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_CHANNEL_CATEGORY"."CHANNEL_CATEGORY_ID" IS '채널카테고리ID';

COMMENT ON COLUMN "BHUB_CHANNEL_CATEGORY"."CHANNEL_CD" IS '채널코드';

COMMENT ON COLUMN "BHUB_CHANNEL_CATEGORY"."PR_CATEGORY_ID" IS '상위채널카테고리ID';

COMMENT ON COLUMN "BHUB_CHANNEL_CATEGORY"."CATEGORY_CD" IS '채널카테고리코드';

COMMENT ON COLUMN "BHUB_CHANNEL_CATEGORY"."CATEGORY_NM" IS '채널카테고리명';

COMMENT ON COLUMN "BHUB_CHANNEL_CATEGORY"."CATEGORY_PATH" IS '카테고리경로';

COMMENT ON COLUMN "BHUB_CHANNEL_CATEGORY"."CATEGORY_LVL" IS '카테고리레벨';

COMMENT ON COLUMN "BHUB_CHANNEL_CATEGORY"."LEAF_YN" IS '최하위여부';

COMMENT ON COLUMN "BHUB_CHANNEL_CATEGORY"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_CHANNEL_CATEGORY"."SORT_SEQ" IS '정렬순서';

COMMENT ON COLUMN "BHUB_CHANNEL_CATEGORY"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_CHANNEL_CATEGORY"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_CHANNEL_CATEGORY"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_CHANNEL_CATEGORY"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_CHANNEL_CATEGORY"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_ITEM_RAW" (
	"RAWITEM_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"RAW_PRODUCT_ID"	VARCHAR2(30)		NOT NULL,
	"EXTITEM_ID"	VARCHAR2(100)		NULL,
	"EXTITEM_CD"	VARCHAR2(100)		NULL,
	"EXTITEM_NM"	VARCHAR2(500)		NULL,
	"EXT_OPTION_NM"	VARCHAR2(500)		NULL,
	"EXT_OPTION_VALUE"	VARCHAR2(1000)		NULL,
	"BAR_CD"	VARCHAR2(50)		NULL,
	"SALE_PRC_AMT"	NUMBER(18,0)		NULL,
	"STOCK_QTY"	NUMBER(18,0)		NULL,
	"SALE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"MATCH_STATUS_CD"	VARCHAR2(20)	DEFAULT 'READY'	NOT NULL,
	"MATCH_SCORE"	NUMBER(10,4)		NULL,
	"CONFIRM_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"CONFIRM_USER_ID"	VARCHAR2(20)		NULL,
	"CONFIRM_DATETIME"	DATE		NULL,
	"RAW_DATA_JSON"	CLOB		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_ITEM_RAW"."RAWITEM_ID" IS '원본ITEM';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."RAW_PRODUCT_ID" IS '원본상품ID';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."EXTITEM_ID" IS '외부ITEM';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."EXTITEM_CD" IS '외부ITEM';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."EXTITEM_NM" IS '외부ITEM명';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."EXT_OPTION_NM" IS '외부옵션명';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."EXT_OPTION_VALUE" IS '외부옵션값';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."BAR_CD" IS '외부바코드';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."SALE_PRC_AMT" IS '외부ITEM';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."STOCK_QTY" IS '외부재고수량';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."SALE_YN" IS '판매여부';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."MATCH_STATUS_CD" IS '매핑상태코드';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."MATCH_SCORE" IS '자동매칭점수';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."CONFIRM_YN" IS '검수확정여부';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."CONFIRM_USER_ID" IS '검수확정자';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."CONFIRM_DATETIME" IS '검수확정일시';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."RAW_DATA_JSON" IS '원본JSON';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_ITEM_RAW"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_ORDER_ITEM" (
	"ORDER_PRODUCT_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"ORDER_ID"	VARCHAR2(30)		NOT NULL,
	"ORDER_LINE_NO"	NUMBER(18,0)		NOT NULL,
	"CHANNEL_ORDER_ID"	VARCHAR2(100)		NOT NULL,
	"CHANNEL_ORDER_SEQ"	VARCHAR2(50)		NULL,
	"PRODUCT_ID"	VARCHAR2(30)		NULL,
	"ITEM_ID"	VARCHAR2(30)		NULL,
	"PRODUCT_CD"	VARCHAR2(100)		NULL,
	"PRODUCT_NM"	VARCHAR2(300)		NULL,
	"OPTION_NM"	VARCHAR2(400)		NULL,
	"ORDER_QTY"	NUMBER(18,0)		NULL,
	"ORDER_PRC"	NUMBER(18,0)		NULL,
	"ORDER_AMT"	NUMBER(18,0)		NULL,
	"DELV_COST"	NUMBER(18,0)		NULL,
	"STATUS_CD"	VARCHAR2(20)		NULL,
	"ITEM_MAP_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"PROC_ERR_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"PROC_ERR_MSG"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."ORDER_PRODUCT_ID" IS '주문상세ID';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."ORDER_ID" IS '주문ID';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."ORDER_LINE_NO" IS '주문라인순번';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."CHANNEL_ORDER_ID" IS '채널주문번호';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."CHANNEL_ORDER_SEQ" IS '채널주문순번';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."ITEM_ID" IS 'ITEM';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."PRODUCT_CD" IS '상품코드';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."PRODUCT_NM" IS '상품명';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."OPTION_NM" IS '옵션명';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."ORDER_QTY" IS '주문수량';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."ORDER_PRC" IS '주문단가';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."ORDER_AMT" IS '주문금액';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."DELV_COST" IS '배송비';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."STATUS_CD" IS '상태코드';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."ITEM_MAP_YN" IS '품목매핑여부';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."PROC_ERR_YN" IS '처리오류여부';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."PROC_ERR_MSG" IS '처리오류메시지';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_ORDER_ITEM"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_PRODUCT_HIST" (
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"ITEM_HIST_ID"	VARCHAR2(30)		NOT NULL,
	"HIST_TP"	VARCHAR2(20)		NOT NULL,
	"PRODUCT_ID"	VARCHAR2(30)		NULL,
	"ITEM_ID"	VARCHAR2(30)		NULL,
	"CHANGE_TP"	VARCHAR2(20)		NOT NULL,
	"CHANGE_DT"	DATE		NOT NULL,
	"CHANGE_USER_ID"	VARCHAR2(20)		NULL,
	"CHANGE_REASON"	VARCHAR2(1000)		NULL,
	"BEFORE_JSON"	CLOB		NULL,
	"AFTER_JSON"	CLOB		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_PRODUCT_HIST"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_PRODUCT_HIST"."ITEM_HIST_ID" IS '상품이력ID';

COMMENT ON COLUMN "BHUB_PRODUCT_HIST"."HIST_TP" IS '이력유형(PRODUCT/ITEM/PRICE/ATTR/IMAGE)';

COMMENT ON COLUMN "BHUB_PRODUCT_HIST"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "BHUB_PRODUCT_HIST"."ITEM_ID" IS 'ITEM';

COMMENT ON COLUMN "BHUB_PRODUCT_HIST"."CHANGE_TP" IS '변경유형(INSERT/UPDATE/DELETE/STATUS)';

COMMENT ON COLUMN "BHUB_PRODUCT_HIST"."CHANGE_DT" IS '변경일시';

COMMENT ON COLUMN "BHUB_PRODUCT_HIST"."CHANGE_USER_ID" IS '변경자';

COMMENT ON COLUMN "BHUB_PRODUCT_HIST"."CHANGE_REASON" IS '변경사유';

COMMENT ON COLUMN "BHUB_PRODUCT_HIST"."BEFORE_JSON" IS '변경전JSON';

COMMENT ON COLUMN "BHUB_PRODUCT_HIST"."AFTER_JSON" IS '변경후JSON';

COMMENT ON COLUMN "BHUB_PRODUCT_HIST"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_PRODUCT_HIST"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_PRODUCT_HIST"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_PRODUCT_HIST"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_PRODUCT_HIST"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_PRODUCT_HIST"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_CHANNEL_ACCOUNT" (
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"CHANNEL_ACCOUNT_ID"	VARCHAR2(30)		NOT NULL,
	"CHANNEL_CD"	VARCHAR2(20)		NOT NULL,
	"ACCOUNT_NM"	VARCHAR2(100)		NOT NULL,
	"SHOP_ID"	VARCHAR2(100)		NULL,
	"SHOP_PW"	VARCHAR2(100)		NULL,
	"SHOP_ID2"	VARCHAR2(100)		NULL,
	"SHOP_PW2"	VARCHAR2(100)		NULL,
	"AUTH_KEY"	VARCHAR2(200)		NULL,
	"AUTH_KEY2"	VARCHAR2(200)		NULL,
	"SHOP_URL"	VARCHAR2(300)		NULL,
	"WAREHOUSE_CD"	VARCHAR2(10)		NULL,
	"ORDER_TP"	VARCHAR2(20)		NULL,
	"DLV_TP"	VARCHAR2(20)		NULL,
	"DLV_COMP_CD"	VARCHAR2(20)		NULL,
	"BUY_CONFIRM_DAY"	NUMBER(18,0)		NULL,
	"STATUS_CD"	VARCHAR2(20)		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."CHANNEL_ACCOUNT_ID" IS '채널계정ID';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."CHANNEL_CD" IS '채널코드';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."ACCOUNT_NM" IS '계정명';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."SHOP_ID" IS '로그인ID1';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."SHOP_PW" IS '로그인PW1';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."SHOP_ID2" IS '로그인ID2';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."SHOP_PW2" IS '로그인PW2';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."AUTH_KEY" IS '인증키1';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."AUTH_KEY2" IS '인증키2';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."SHOP_URL" IS '쇼핑몰URL';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."WAREHOUSE_CD" IS '기본창고코드';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."ORDER_TP" IS '주문구분';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."DLV_TP" IS '배송구분';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."DLV_COMP_CD" IS '택배사코드';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."BUY_CONFIRM_DAY" IS '구매확정일';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."STATUS_CD" IS '계정상태코드';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_CHANNEL_ACCOUNT"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_PRODUCT_COMPONENT" (
	"COMPONENT_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"PRODUCT_ID"	VARCHAR2(30)		NOT NULL,
	"ITEM_ID"	VARCHAR2(30)		NULL,
	"COMPONENT_TP"	VARCHAR2(20)		NOT NULL,
	"COMPONENT_NM"	VARCHAR2(200)		NOT NULL,
	"REP_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"SALE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"STOCK_DEDUCT_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT"."COMPONENT_ID" IS '구성ID';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT"."ITEM_ID" IS 'ITEM';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT"."COMPONENT_TP" IS '구성유형(SET/BUNDLE/PACK/GIFT)';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT"."COMPONENT_NM" IS '구성명';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT"."REP_YN" IS '대표구성여부';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT"."SALE_YN" IS '판매사용여부';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT"."STOCK_DEDUCT_YN" IS '재고차감적용여부';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_CHANNEL_ITEM" (
	"CHANNELITEM_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"CHANNEL_PRODUCT_ID"	VARCHAR2(30)		NOT NULL,
	"ITEM_ID"	VARCHAR2(30)		NOT NULL,
	"CHANNEL_OPTION_ID"	VARCHAR2(100)		NULL,
	"CHANNEL_OPTION_NM"	VARCHAR2(300)		NULL,
	"CHANNEL_ITEM_CD"	VARCHAR2(100)		NULL,
	"SALE_PRC_AMT"	NUMBER(18,0)		NULL,
	"SORT_SEQ"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_CHANNEL_ITEM"."CHANNELITEM_ID" IS '채널품목ITEM';

COMMENT ON COLUMN "BHUB_CHANNEL_ITEM"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_CHANNEL_ITEM"."CHANNEL_PRODUCT_ID" IS '채널상품ID';

COMMENT ON COLUMN "BHUB_CHANNEL_ITEM"."ITEM_ID" IS 'ITEM';

COMMENT ON COLUMN "BHUB_CHANNEL_ITEM"."CHANNEL_OPTION_ID" IS '채널옵션ID';

COMMENT ON COLUMN "BHUB_CHANNEL_ITEM"."CHANNEL_OPTION_NM" IS '채널옵션명';

COMMENT ON COLUMN "BHUB_CHANNEL_ITEM"."CHANNEL_ITEM_CD" IS '채널ITEM코드';

COMMENT ON COLUMN "BHUB_CHANNEL_ITEM"."SALE_PRC_AMT" IS '채널판매가';

COMMENT ON COLUMN "BHUB_CHANNEL_ITEM"."SORT_SEQ" IS '정렬순서';

COMMENT ON COLUMN "BHUB_CHANNEL_ITEM"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_CHANNEL_ITEM"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_CHANNEL_ITEM"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_CHANNEL_ITEM"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_CHANNEL_ITEM"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_CATEGORY_CHANNEL_MAP" (
	"MAP_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"CATEGORY_ID"	VARCHAR2(30)		NOT NULL,
	"CHANNEL_CD"	VARCHAR2(20)		NOT NULL,
	"CHANNEL_CATEGORY_ID"	VARCHAR2(30)		NOT NULL,
	"PRIMARY_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"AUTO_APPLY_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_CATEGORY_CHANNEL_MAP"."MAP_ID" IS '매핑ID';

COMMENT ON COLUMN "BHUB_CATEGORY_CHANNEL_MAP"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_CATEGORY_CHANNEL_MAP"."CATEGORY_ID" IS '표준카테고리ID';

COMMENT ON COLUMN "BHUB_CATEGORY_CHANNEL_MAP"."CHANNEL_CD" IS '채널코드';

COMMENT ON COLUMN "BHUB_CATEGORY_CHANNEL_MAP"."CHANNEL_CATEGORY_ID" IS '채널카테고리ID';

COMMENT ON COLUMN "BHUB_CATEGORY_CHANNEL_MAP"."PRIMARY_YN" IS '대표매핑여부';

COMMENT ON COLUMN "BHUB_CATEGORY_CHANNEL_MAP"."AUTO_APPLY_YN" IS '자동적용여부';

COMMENT ON COLUMN "BHUB_CATEGORY_CHANNEL_MAP"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_CATEGORY_CHANNEL_MAP"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_CATEGORY_CHANNEL_MAP"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_CATEGORY_CHANNEL_MAP"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_CATEGORY_CHANNEL_MAP"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_CATEGORY_CHANNEL_MAP"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_OPTION_VALUE" (
	"OPTION_VALUE_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"OPTION_ID"	VARCHAR2(30)		NOT NULL,
	"VALUE_CD"	VARCHAR2(50)		NOT NULL,
	"VALUE_NM"	VARCHAR2(100)		NOT NULL,
	"SORT_SEQ"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_OPTION_VALUE"."OPTION_VALUE_ID" IS '옵션값ID';

COMMENT ON COLUMN "BHUB_OPTION_VALUE"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_OPTION_VALUE"."OPTION_ID" IS '옵션ID';

COMMENT ON COLUMN "BHUB_OPTION_VALUE"."VALUE_CD" IS '옵션값코드';

COMMENT ON COLUMN "BHUB_OPTION_VALUE"."VALUE_NM" IS '옵션값명';

COMMENT ON COLUMN "BHUB_OPTION_VALUE"."SORT_SEQ" IS '정렬순서';

COMMENT ON COLUMN "BHUB_OPTION_VALUE"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_OPTION_VALUE"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_OPTION_VALUE"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_OPTION_VALUE"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_OPTION_VALUE"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_OPTION_VALUE"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_PRODUCT_COMPONENT_ITEM" (
	"COMPONENT_PRODUCT_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"COMPONENT_ID"	VARCHAR2(30)		NOT NULL,
	"PARENT_PRODUCT_ID"	VARCHAR2(30)		NULL,
	"PARENTITEM_ID"	VARCHAR2(30)		NULL,
	"CHILD_PRODUCT_ID"	VARCHAR2(30)		NULL,
	"CHILDITEM_ID"	VARCHAR2(30)		NOT NULL,
	"COMPONENT_QTY"	NUMBER(18,0)	DEFAULT 1	NOT NULL,
	"REQUIRED_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"STOCK_DEDUCT_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"GIFT_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"SORT_SEQ"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."COMPONENT_PRODUCT_ID" IS '구성상세ID';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."COMPONENT_ID" IS '구성ID';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."PARENT_PRODUCT_ID" IS '부모상품ID';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."PARENTITEM_ID" IS '부모ITEM';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."CHILD_PRODUCT_ID" IS '자식상품ID';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."CHILDITEM_ID" IS '자식ITEM';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."COMPONENT_QTY" IS '구성수량';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."REQUIRED_YN" IS '필수구성여부';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."STOCK_DEDUCT_YN" IS '재고차감여부';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."GIFT_YN" IS '사은품여부';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."SORT_SEQ" IS '정렬순서';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_PRODUCT_COMPONENT_ITEM"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_ITEM_STYLE_OPTION" (
	"ITEM_STYLE_OPTION_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"ITEM_STYLE_ID"	VARCHAR2(30)		NOT NULL,
	"OPTION_ID"	VARCHAR2(30)		NOT NULL,
	"DISPLAY_OPTION_NM"	VARCHAR2(100)		NULL,
	"REQUIRED_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"SORT_SEQ"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION"."ITEM_STYLE_OPTION_ID" IS 'ITEM스타일옵션ID';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION"."ITEM_STYLE_ID" IS 'ITEM스타일ID';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION"."OPTION_ID" IS '옵션ID';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION"."DISPLAY_OPTION_NM" IS '표시옵션명';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION"."REQUIRED_YN" IS '필수여부';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION"."SORT_SEQ" IS '정렬순서';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_CHANNEL_PRODUCT" (
	"CHANNEL_PRODUCT_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"CHANNEL_ACCOUNT_ID"	VARCHAR2(30)		NOT NULL,
	"PRODUCT_ID"	VARCHAR2(30)		NOT NULL,
	"CHANNEL_GOODS_ID"	VARCHAR2(100)		NULL,
	"CHANNEL_GOODS_NM"	VARCHAR2(200)		NULL,
	"CHANNEL_CATEGORY_CD"	VARCHAR2(50)		NULL,
	"SALE_STATUS_CD"	VARCHAR2(20)		NULL,
	"APPROVAL_STATUS_CD"	VARCHAR2(20)		NULL,
	"DISPLAY_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"LAST_SEND_DT"	DATE		NULL,
	"LAST_SEND_RESULT_CD"	VARCHAR2(20)		NULL,
	"LAST_SEND_MSG"	VARCHAR2(1000)		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."CHANNEL_PRODUCT_ID" IS '채널상품ID';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."CHANNEL_ACCOUNT_ID" IS '채널계정ID';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."CHANNEL_GOODS_ID" IS '채널상품ID';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."CHANNEL_GOODS_NM" IS '채널상품명';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."CHANNEL_CATEGORY_CD" IS '채널카테고리코드';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."SALE_STATUS_CD" IS '판매상태코드';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."APPROVAL_STATUS_CD" IS '승인상태코드';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."DISPLAY_YN" IS '노출여부';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."LAST_SEND_DT" IS '최종전송일시';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."LAST_SEND_RESULT_CD" IS '최종전송결과코드';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."LAST_SEND_MSG" IS '최종전송메시지';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_CHANNEL_PRODUCT"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_PRODUCT_MATCH" (
	"MATCH_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"MATCH_TP"	VARCHAR2(20)		NOT NULL,
	"RAW_PRODUCT_ID"	VARCHAR2(30)		NULL,
	"RAWITEM_ID"	VARCHAR2(30)		NULL,
	"PRODUCT_ID"	VARCHAR2(30)		NULL,
	"ITEM_ID"	VARCHAR2(30)		NULL,
	"MATCH_METHOD_CD"	VARCHAR2(20)		NOT NULL,
	"MATCH_SCORE"	NUMBER(10,4)		NULL,
	"PRIMARY_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"CONFIRM_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"CONFIRM_USER_ID"	VARCHAR2(20)		NULL,
	"CONFIRM_DATETIME"	DATE		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."MATCH_ID" IS '매핑ID';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."MATCH_TP" IS '매핑유형(PRODUCT/ITEM)';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."RAW_PRODUCT_ID" IS '원본상품ID';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."RAWITEM_ID" IS '원본ITEM';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."PRODUCT_ID" IS '내부상품ID';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."ITEM_ID" IS '내부ITEM';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."MATCH_METHOD_CD" IS '매칭방식코드';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."MATCH_SCORE" IS '매칭점수';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."PRIMARY_YN" IS '대표매핑여부';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."CONFIRM_YN" IS '확정여부';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."CONFIRM_USER_ID" IS '확정자';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."CONFIRM_DATETIME" IS '확정일시';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_PRODUCT_MATCH"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_PRODUCT_RAW" (
	"RAW_PRODUCT_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"BATCH_ID"	VARCHAR2(30)		NULL,
	"CHANNEL_ACCOUNT_ID"	VARCHAR2(30)		NOT NULL,
	"CHANNEL_CD"	VARCHAR2(20)		NOT NULL,
	"EXT_PRODUCT_ID"	VARCHAR2(100)		NULL,
	"EXT_PRODUCT_CD"	VARCHAR2(100)		NULL,
	"EXT_PRODUCT_NM"	VARCHAR2(500)		NOT NULL,
	"EXT_BRAND_NM"	VARCHAR2(200)		NULL,
	"EXT_MODEL_NM"	VARCHAR2(200)		NULL,
	"EXT_CATEGORY_CD"	VARCHAR2(100)		NULL,
	"EXT_CATEGORY_PATH"	VARCHAR2(1000)		NULL,
	"SALE_STATUS_CD"	VARCHAR2(20)		NULL,
	"APPROVAL_STATUS_CD"	VARCHAR2(20)		NULL,
	"SALE_PRC_AMT"	NUMBER(18,0)		NULL,
	"CONSUMER_PRC_AMT"	NUMBER(18,0)		NULL,
	"DELV_COST_AMT"	NUMBER(18,0)		NULL,
	"IMAGE_URL"	VARCHAR2(500)		NULL,
	"DESCRIPTION_HTML"	CLOB		NULL,
	"RAW_DATA_JSON"	CLOB		NULL,
	"MATCH_STATUS_CD"	VARCHAR2(20)	DEFAULT 'READY'	NOT NULL,
	"MATCH_SCORE"	NUMBER(10,4)		NULL,
	"CONFIRM_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"CONFIRM_USER_ID"	VARCHAR2(20)		NULL,
	"CONFIRM_DATETIME"	DATE		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."RAW_PRODUCT_ID" IS '원본상품ID';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."BATCH_ID" IS '수집배치ID';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."CHANNEL_ACCOUNT_ID" IS '채널계정ID';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."CHANNEL_CD" IS '채널코드';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."EXT_PRODUCT_ID" IS '외부상품ID';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."EXT_PRODUCT_CD" IS '외부상품코드';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."EXT_PRODUCT_NM" IS '외부상품명';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."EXT_BRAND_NM" IS '외부브랜드명';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."EXT_MODEL_NM" IS '외부모델명';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."EXT_CATEGORY_CD" IS '외부카테고리코드';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."EXT_CATEGORY_PATH" IS '외부카테고리경로';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."SALE_STATUS_CD" IS '외부판매상태코드';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."APPROVAL_STATUS_CD" IS '외부승인상태코드';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."SALE_PRC_AMT" IS '외부판매가';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."CONSUMER_PRC_AMT" IS '외부소비자가';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."DELV_COST_AMT" IS '외부배송비';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."IMAGE_URL" IS '대표이미지URL';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."DESCRIPTION_HTML" IS '상세설명HTML';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."RAW_DATA_JSON" IS '원본JSON';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."MATCH_STATUS_CD" IS '매핑상태코드';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."MATCH_SCORE" IS '자동매칭점수';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."CONFIRM_YN" IS '검수확정여부';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."CONFIRM_USER_ID" IS '검수확정자';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."CONFIRM_DATETIME" IS '검수확정일시';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_PRODUCT_RAW"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_PRODUCT_IMAGE" (
	"IMAGE_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"PRODUCT_ID"	VARCHAR2(30)		NOT NULL,
	"ITEM_ID"	VARCHAR2(30)		NULL,
	"IMAGE_TP"	VARCHAR2(20)		NOT NULL,
	"IMAGE_URL"	VARCHAR2(500)		NOT NULL,
	"IMAGE_FILE_NM"	VARCHAR2(200)		NULL,
	"REP_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"SORT_SEQ"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_PRODUCT_IMAGE"."IMAGE_ID" IS '이미지ID';

COMMENT ON COLUMN "BHUB_PRODUCT_IMAGE"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_PRODUCT_IMAGE"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "BHUB_PRODUCT_IMAGE"."ITEM_ID" IS 'ITEM';

COMMENT ON COLUMN "BHUB_PRODUCT_IMAGE"."IMAGE_TP" IS '이미지유형';

COMMENT ON COLUMN "BHUB_PRODUCT_IMAGE"."IMAGE_URL" IS '이미지URL';

COMMENT ON COLUMN "BHUB_PRODUCT_IMAGE"."IMAGE_FILE_NM" IS '이미지파일명';

COMMENT ON COLUMN "BHUB_PRODUCT_IMAGE"."REP_YN" IS '대표이미지여부';

COMMENT ON COLUMN "BHUB_PRODUCT_IMAGE"."SORT_SEQ" IS '정렬순서';

COMMENT ON COLUMN "BHUB_PRODUCT_IMAGE"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_PRODUCT_IMAGE"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_PRODUCT_IMAGE"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_PRODUCT_IMAGE"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_PRODUCT_IMAGE"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_PRODUCT_IMAGE"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_CHANNEL_SEND_BATCH" (
	"SEND_BATCH_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"CHANNEL_ACCOUNT_ID"	VARCHAR2(30)		NOT NULL,
	"SEND_TP"	VARCHAR2(20)		NOT NULL,
	"TARGET_TP"	VARCHAR2(20)		NOT NULL,
	"REQUEST_DT"	DATE		NULL,
	"START_DT"	DATE		NULL,
	"END_DT"	DATE		NULL,
	"STATUS_CD"	VARCHAR2(20)		NOT NULL,
	"TOTAL_CNT"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"SUCCESS_CNT"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"FAIL_CNT"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"SKIP_CNT"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"REQUEST_JSON"	CLOB		NULL,
	"RESULT_MSG"	VARCHAR2(2000)		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."SEND_BATCH_ID" IS '전송배치ID';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."CHANNEL_ACCOUNT_ID" IS '채널계정ID';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."SEND_TP" IS '전송유형(REG/UPD/DEL/STOP/SALE)';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."TARGET_TP" IS '대상유형(PRODUCT/ITEM)';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."REQUEST_DT" IS '전송요청일시';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."START_DT" IS '전송시작일시';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."END_DT" IS '전송종료일시';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."STATUS_CD" IS '배치상태코드';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."TOTAL_CNT" IS '총대상건수';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."SUCCESS_CNT" IS '성공건수';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."FAIL_CNT" IS '실패건수';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."SKIP_CNT" IS '건너뜀건수';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."REQUEST_JSON" IS '요청JSON';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."RESULT_MSG" IS '결과메시지';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_BATCH"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_CHANNEL_SEND_HIST" (
	"SEND_HIST_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"SEND_BATCH_ID"	VARCHAR2(30)		NULL,
	"CHANNEL_ACCOUNT_ID"	VARCHAR2(30)		NOT NULL,
	"CHANNEL_PRODUCT_ID"	VARCHAR2(30)		NULL,
	"CHANNELITEM_ID"	VARCHAR2(30)		NULL,
	"PRODUCT_ID"	VARCHAR2(30)		NULL,
	"ITEM_ID"	VARCHAR2(30)		NULL,
	"SEND_TP"	VARCHAR2(20)		NOT NULL,
	"REQUEST_DT"	DATE		NULL,
	"RESPONSE_DT"	DATE		NULL,
	"SUCCESS_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"RESULT_CD"	VARCHAR2(50)		NULL,
	"RESULT_MSG"	VARCHAR2(2000)		NULL,
	"REQUEST_JSON"	CLOB		NULL,
	"RESPONSE_JSON"	CLOB		NULL,
	"RETRY_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."SEND_HIST_ID" IS '전송이력ID';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."SEND_BATCH_ID" IS '전송배치ID';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."CHANNEL_ACCOUNT_ID" IS '채널계정ID';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."CHANNEL_PRODUCT_ID" IS '채널상품ID';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."CHANNELITEM_ID" IS '채널ITEM';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."ITEM_ID" IS 'ITEM';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."SEND_TP" IS '전송유형';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."REQUEST_DT" IS '전송요청일시';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."RESPONSE_DT" IS '응답일시';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."SUCCESS_YN" IS '성공여부';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."RESULT_CD" IS '결과코드';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."RESULT_MSG" IS '결과메시지';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."REQUEST_JSON" IS '요청JSON';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."RESPONSE_JSON" IS '응답JSON';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."RETRY_YN" IS '재시도여부';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_CHANNEL_SEND_HIST"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_ITEM" (
	"ITEM_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"ITEM_CD"	VARCHAR2(30)		NOT NULL,
	"ITEM_NM"	VARCHAR2(200)		NOT NULL,
	"ITEM_ALIAS"	VARCHAR2(100)		NULL,
	"BAR_CD"	VARCHAR2(30)		NULL,
	"BAR_CD2"	VARCHAR2(30)		NULL,
	"BAR_CD3"	VARCHAR2(30)		NULL,
	"BAR_CD4"	VARCHAR2(30)		NULL,
	"OPTION_SUMMARY"	VARCHAR2(500)		NULL,
	"SALE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"STOCK_USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"SOLDOUT_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"SET_ITEM_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"WEIGHT_QTY"	NUMBER(18,0)		NULL,
	"WIDTH_QTY"	NUMBER(18,0)		NULL,
	"LENGTH_QTY"	NUMBER(18,0)		NULL,
	"HEIGHT_QTY"	NUMBER(18,0)		NULL,
	"SORT_SEQ"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL,
	"ITEM_STYLE_ID"	VARCHAR2(30)		NULL
);

COMMENT ON COLUMN "BHUB_ITEM"."ITEM_ID" IS 'ITEM';

COMMENT ON COLUMN "BHUB_ITEM"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_ITEM"."ITEM_CD" IS 'ITEM';

COMMENT ON COLUMN "BHUB_ITEM"."ITEM_NM" IS 'ITEM명';

COMMENT ON COLUMN "BHUB_ITEM"."ITEM_ALIAS" IS 'ITEM';

COMMENT ON COLUMN "BHUB_ITEM"."BAR_CD" IS '바코드1';

COMMENT ON COLUMN "BHUB_ITEM"."BAR_CD2" IS '바코드2';

COMMENT ON COLUMN "BHUB_ITEM"."BAR_CD3" IS '바코드3';

COMMENT ON COLUMN "BHUB_ITEM"."BAR_CD4" IS '바코드4';

COMMENT ON COLUMN "BHUB_ITEM"."OPTION_SUMMARY" IS '옵션요약';

COMMENT ON COLUMN "BHUB_ITEM"."SALE_YN" IS '판매여부';

COMMENT ON COLUMN "BHUB_ITEM"."STOCK_USE_YN" IS '재고사용여부';

COMMENT ON COLUMN "BHUB_ITEM"."SOLDOUT_YN" IS '품절여부';

COMMENT ON COLUMN "BHUB_ITEM"."SET_ITEM_YN" IS '세트품목여부';

COMMENT ON COLUMN "BHUB_ITEM"."WEIGHT_QTY" IS '중량';

COMMENT ON COLUMN "BHUB_ITEM"."WIDTH_QTY" IS '가로';

COMMENT ON COLUMN "BHUB_ITEM"."LENGTH_QTY" IS '세로';

COMMENT ON COLUMN "BHUB_ITEM"."HEIGHT_QTY" IS '높이';

COMMENT ON COLUMN "BHUB_ITEM"."SORT_SEQ" IS '정렬순서';

COMMENT ON COLUMN "BHUB_ITEM"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_ITEM"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_ITEM"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_ITEM"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_ITEM"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_ITEM"."UPDATE_DATETIME" IS '수정일시';

COMMENT ON COLUMN "BHUB_ITEM"."ITEM_STYLE_ID" IS 'ITEM스타일ID';

CREATE TABLE "BHUB_ORDER_SEND" (
	"ORDER_SEND_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"ORDER_ID"	VARCHAR2(30)		NOT NULL,
	"SEND_TP"	VARCHAR2(20)		NOT NULL,
	"SEND_STAT_CD"	VARCHAR2(20)		NOT NULL,
	"REQUEST_PAYLOAD"	CLOB		NULL,
	"RESPONSE_PAYLOAD"	CLOB		NULL,
	"REQUEST_DT"	DATE		NULL,
	"SEND_DT"	DATE		NULL,
	"RESPONSE_DT"	DATE		NULL,
	"SUCCESS_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"RESULT_CD"	VARCHAR2(50)		NULL,
	"RESULT_MSG"	VARCHAR2(2000)		NULL,
	"ERROR_MSG"	VARCHAR2(4000)		NULL,
	"RETRY_CNT"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"RETRY_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"IDEMPOTENCY_KEY"	VARCHAR2(100)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_ORDER_SEND"."ORDER_SEND_ID" IS '주문전송ID';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."ORDER_ID" IS '주문ID';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."SEND_TP" IS '전송유형';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."SEND_STAT_CD" IS '전송상태코드';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."REQUEST_PAYLOAD" IS '요청데이터';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."RESPONSE_PAYLOAD" IS '응답데이터';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."REQUEST_DT" IS '요청일시';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."SEND_DT" IS '전송일시';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."RESPONSE_DT" IS '응답일시';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."SUCCESS_YN" IS '성공여부';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."RESULT_CD" IS '결과코드';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."RESULT_MSG" IS '결과메시지';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."ERROR_MSG" IS '에러메시지';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."RETRY_CNT" IS '재시도횟수';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."RETRY_YN" IS '재처리여부';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."IDEMPOTENCY_KEY" IS '중복전송방지키';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_ORDER_SEND"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_PRODUCT_ITEM" (
	"PRODUCT_ITEM_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"PRODUCT_ID"	VARCHAR2(30)		NOT NULL,
	"ITEM_ID"	VARCHAR2(30)		NOT NULL,
	"PRODUCT_ITEM_NM"	VARCHAR2(200)		NULL,
	"OPTION_SUMMARY"	VARCHAR2(500)		NULL,
	"SALE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"DISPLAY_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"SOLDOUT_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"REP_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"SORT_SEQ"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_PRODUCT_ITEM"."PRODUCT_ITEM_ID" IS '상품ITEM연결ID';

COMMENT ON COLUMN "BHUB_PRODUCT_ITEM"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_PRODUCT_ITEM"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "BHUB_PRODUCT_ITEM"."ITEM_ID" IS 'ITEM';

COMMENT ON COLUMN "BHUB_PRODUCT_ITEM"."PRODUCT_ITEM_NM" IS '상품별';

COMMENT ON COLUMN "BHUB_PRODUCT_ITEM"."OPTION_SUMMARY" IS '상품별';

COMMENT ON COLUMN "BHUB_PRODUCT_ITEM"."SALE_YN" IS '상품';

COMMENT ON COLUMN "BHUB_PRODUCT_ITEM"."DISPLAY_YN" IS '상품';

COMMENT ON COLUMN "BHUB_PRODUCT_ITEM"."SOLDOUT_YN" IS '상품';

COMMENT ON COLUMN "BHUB_PRODUCT_ITEM"."REP_YN" IS '대표';

COMMENT ON COLUMN "BHUB_PRODUCT_ITEM"."SORT_SEQ" IS '정렬순서';

COMMENT ON COLUMN "BHUB_PRODUCT_ITEM"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_PRODUCT_ITEM"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_PRODUCT_ITEM"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_PRODUCT_ITEM"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_PRODUCT_ITEM"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_PRODUCT_ITEM"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_PRODUCT" (
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"PRODUCT_ID"	VARCHAR2(30)		NOT NULL,
	"PRODUCT_CD"	VARCHAR2(30)		NOT NULL,
	"PRODUCT_NM"	VARCHAR2(200)		NOT NULL,
	"DISP_PRODUCT_NM"	VARCHAR2(200)		NULL,
	"PRODUCT_SHORT_NM"	VARCHAR2(100)		NULL,
	"BRAND_CD"	VARCHAR2(20)		NULL,
	"CATEGORY_ID"	VARCHAR2(30)		NULL,
	"PRODUCT_TP"	VARCHAR2(20)		NULL,
	"STATUS_CD"	VARCHAR2(20)		NULL,
	"SALE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"DISPLAY_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"TAX_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"ORIGIN_NM"	VARCHAR2(100)		NULL,
	"MAKER_NM"	VARCHAR2(100)		NULL,
	"MODEL_NM"	VARCHAR2(100)		NULL,
	"MODEL_NO"	VARCHAR2(100)		NULL,
	"DESCRIPTION_HTML"	CLOB		NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_PRODUCT"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_PRODUCT"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "BHUB_PRODUCT"."PRODUCT_CD" IS '상품코드';

COMMENT ON COLUMN "BHUB_PRODUCT"."PRODUCT_NM" IS '상품명';

COMMENT ON COLUMN "BHUB_PRODUCT"."DISP_PRODUCT_NM" IS '노출상품명';

COMMENT ON COLUMN "BHUB_PRODUCT"."PRODUCT_SHORT_NM" IS '상품약칭';

COMMENT ON COLUMN "BHUB_PRODUCT"."BRAND_CD" IS '브랜드코드';

COMMENT ON COLUMN "BHUB_PRODUCT"."CATEGORY_ID" IS '표준카테고리ID';

COMMENT ON COLUMN "BHUB_PRODUCT"."PRODUCT_TP" IS '상품유형';

COMMENT ON COLUMN "BHUB_PRODUCT"."STATUS_CD" IS '상품상태코드';

COMMENT ON COLUMN "BHUB_PRODUCT"."SALE_YN" IS '판매여부';

COMMENT ON COLUMN "BHUB_PRODUCT"."DISPLAY_YN" IS '노출여부';

COMMENT ON COLUMN "BHUB_PRODUCT"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_PRODUCT"."TAX_YN" IS '과세여부';

COMMENT ON COLUMN "BHUB_PRODUCT"."ORIGIN_NM" IS '원산지명';

COMMENT ON COLUMN "BHUB_PRODUCT"."MAKER_NM" IS '제조사명';

COMMENT ON COLUMN "BHUB_PRODUCT"."MODEL_NM" IS '모델명';

COMMENT ON COLUMN "BHUB_PRODUCT"."MODEL_NO" IS '모델번호';

COMMENT ON COLUMN "BHUB_PRODUCT"."DESCRIPTION_HTML" IS '상품상세설명HTML';

COMMENT ON COLUMN "BHUB_PRODUCT"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_PRODUCT"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_PRODUCT"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_PRODUCT"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_PRODUCT"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_ITEM_STOCK" (
	"STOCK_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"ITEM_ID"	VARCHAR2(30)		NOT NULL,
	"WAREHOUSE_CD"	VARCHAR2(10)		NOT NULL,
	"ERP_ITEM_CD"	VARCHAR2(30)		NULL,
	"ONHAND_QTY"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"ALLOC_QTY"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"AVAILABLE_QTY"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"SAFETY_QTY"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"IN_TRANSIT_QTY"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"HOLD_QTY"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"SOLDOUT_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"STOCK_SYNC_DT"	DATE		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."STOCK_ID" IS '재고ID';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."ITEM_ID" IS 'ITEM';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."WAREHOUSE_CD" IS '창고코드';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."ERP_ITEM_CD" IS 'ERP';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."ONHAND_QTY" IS '현재고수량';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."ALLOC_QTY" IS '예약수량';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."AVAILABLE_QTY" IS '가용수량';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."SAFETY_QTY" IS '안전재고수량';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."IN_TRANSIT_QTY" IS '이동중수량';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."HOLD_QTY" IS '보류수량';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."SOLDOUT_YN" IS '품절여부';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."STOCK_SYNC_DT" IS '재고동기화일시';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_ITEM_STOCK"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_CHANNEL" (
	"CHANNEL_CD"	VARCHAR2(20)		NOT NULL,
	"CHANNEL_NM"	VARCHAR2(100)		NOT NULL,
	"CHANNEL_TP"	VARCHAR2(20)		NULL,
	"API_PROVIDER"	VARCHAR2(30)		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"SORT_SEQ"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"REMARK_TXT"	VARCHAR2(500)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_CHANNEL"."CHANNEL_CD" IS '채널코드';

COMMENT ON COLUMN "BHUB_CHANNEL"."CHANNEL_NM" IS '채널명';

COMMENT ON COLUMN "BHUB_CHANNEL"."CHANNEL_TP" IS '채널유형';

COMMENT ON COLUMN "BHUB_CHANNEL"."API_PROVIDER" IS 'API';

COMMENT ON COLUMN "BHUB_CHANNEL"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_CHANNEL"."SORT_SEQ" IS '정렬순서';

COMMENT ON COLUMN "BHUB_CHANNEL"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_CHANNEL"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_CHANNEL"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_CHANNEL"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_CHANNEL"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_ITEM_STYLE" (
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"ITEM_STYLE_ID"	VARCHAR2(30)		NOT NULL,
	"STYLE_CD"	VARCHAR2(50)		NOT NULL,
	"STYLE_NM"	VARCHAR2(200)		NOT NULL,
	"BRAND_CD"	VARCHAR2(30)		NULL,
	"CATEGORY_ID"	VARCHAR2(30)		NULL,
	"ITEM_CD_RULE_TXT"	VARCHAR2(500)		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_ITEM_STYLE"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_ITEM_STYLE"."ITEM_STYLE_ID" IS 'ITEM스타일ID';

COMMENT ON COLUMN "BHUB_ITEM_STYLE"."STYLE_CD" IS '스타일코드';

COMMENT ON COLUMN "BHUB_ITEM_STYLE"."STYLE_NM" IS '스타일명';

COMMENT ON COLUMN "BHUB_ITEM_STYLE"."BRAND_CD" IS '브랜드코드';

COMMENT ON COLUMN "BHUB_ITEM_STYLE"."CATEGORY_ID" IS '카테고리ID';

COMMENT ON COLUMN "BHUB_ITEM_STYLE"."ITEM_CD_RULE_TXT" IS 'ITEM코드생성규칙';

COMMENT ON COLUMN "BHUB_ITEM_STYLE"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_ITEM_STYLE"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_ITEM_STYLE"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_ITEM_STYLE"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_ITEM_STYLE"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_ITEM_STYLE"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_PRODUCT_SEND" (
	"SEND_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"SEND_NO"	VARCHAR2(50)		NOT NULL,
	"SEND_TP"	VARCHAR2(20)		NOT NULL,
	"SEND_STAT_CD"	VARCHAR2(20)		NOT NULL,
	"CHANNEL_CD"	VARCHAR2(20)		NOT NULL,
	"CHANNEL_ACCOUNT_ID"	VARCHAR2(30)		NOT NULL,
	"SEND_BATCH_ID"	VARCHAR2(30)		NULL,
	"PRODUCT_ID"	VARCHAR2(30)		NOT NULL,
	"ITEM_ID"	VARCHAR2(30)		NULL,
	"REQUEST_PAYLOAD"	CLOB		NULL,
	"RESPONSE_PAYLOAD"	CLOB		NULL,
	"REQUEST_DT"	DATE		NULL,
	"SEND_DT"	DATE		NULL,
	"RESPONSE_DT"	DATE		NULL,
	"SUCCESS_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"RESULT_CD"	VARCHAR2(50)		NULL,
	"RESULT_MSG"	VARCHAR2(2000)		NULL,
	"ERROR_MSG"	VARCHAR2(4000)		NULL,
	"RETRY_CNT"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"RETRY_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"IDEMPOTENCY_KEY"	VARCHAR2(100)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."SEND_ID" IS '전송ID';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."SEND_NO" IS '전송번호';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."SEND_TP" IS '전송유형';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."SEND_STAT_CD" IS '전송상태코드';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."CHANNEL_CD" IS '채널코드';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."CHANNEL_ACCOUNT_ID" IS '채널계정ID';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."SEND_BATCH_ID" IS '전송배치ID';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."ITEM_ID" IS 'ITEM';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."REQUEST_PAYLOAD" IS '요청데이터(XML/JSON)';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."RESPONSE_PAYLOAD" IS '응답데이터(XML/JSON)';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."REQUEST_DT" IS '요청일시';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."SEND_DT" IS '전송일시';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."RESPONSE_DT" IS '응답일시';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."SUCCESS_YN" IS '성공여부';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."RESULT_CD" IS '결과코드';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."RESULT_MSG" IS '결과메시지';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."ERROR_MSG" IS '에러메시지';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."RETRY_CNT" IS '재시도횟수';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."RETRY_YN" IS '재처리여부';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."IDEMPOTENCY_KEY" IS '중복전송방지키';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_PRODUCT_SEND"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_ITEM_STYLE_OPTION_VALUE" (
	"ITEM_STYLE_OPTION_VALUE_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"ITEM_STYLE_OPTION_ID"	VARCHAR2(30)		NOT NULL,
	"OPTION_VALUE_ID"	VARCHAR2(30)		NOT NULL,
	"DISPLAY_VALUE_NM"	VARCHAR2(100)		NULL,
	"SORT_SEQ"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION_VALUE"."ITEM_STYLE_OPTION_VALUE_ID" IS 'ITEM스타일옵션값ID';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION_VALUE"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION_VALUE"."ITEM_STYLE_OPTION_ID" IS 'ITEM스타일옵션ID';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION_VALUE"."OPTION_VALUE_ID" IS '옵션값ID';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION_VALUE"."DISPLAY_VALUE_NM" IS '표시옵션값명';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION_VALUE"."SORT_SEQ" IS '정렬순서';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION_VALUE"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION_VALUE"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION_VALUE"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION_VALUE"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION_VALUE"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_ITEM_STYLE_OPTION_VALUE"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_ORDER_RAW" (
	"RAW_ORDER_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"BATCH_ID"	VARCHAR2(30)		NULL,
	"RAW_KEY"	VARCHAR2(50)		NOT NULL,
	"ORDER_SEQ"	NUMBER(18,0)	DEFAULT 1	NOT NULL,
	"CHANNEL_CD"	VARCHAR2(20)		NULL,
	"CHANNEL_ACCOUNT_ID"	VARCHAR2(30)		NULL,
	"CHANNEL_ORDER_ID"	VARCHAR2(60)		NOT NULL,
	"CHANNEL_ORDER_SEQ"	VARCHAR2(50)		NULL,
	"ORDER_STATUS"	VARCHAR2(50)		NULL,
	"ORDER_STATUS_CD"	VARCHAR2(10)		NULL,
	"BUYER_NM"	VARCHAR2(50)		NULL,
	"RECEIVE_NAME"	VARCHAR2(50)		NULL,
	"PRODUCT_ID"	VARCHAR2(50)		NULL,
	"ITEM_ID"	VARCHAR2(50)		NULL,
	"ITEM_NAME"	VARCHAR2(200)		NULL,
	"SALE_CNT"	NUMBER(18,0)		NULL,
	"RAW_DATA_JSON"	CLOB		NULL,
	"ERP_IF_YN"	CHAR(1)	DEFAULT '0'	NULL,
	"PROC_ERR_YN"	CHAR(1)	DEFAULT '0'	NULL,
	"CONFIRM_YN"	CHAR(1)	DEFAULT '0'	NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "BHUB_ORDER_RAW"."RAW_ORDER_ID" IS '원본주문ID';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."BATCH_ID" IS '수집배치ID';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."RAW_KEY" IS '원본수집키';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."ORDER_SEQ" IS '주문순번';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."CHANNEL_CD" IS '채널코드';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."CHANNEL_ACCOUNT_ID" IS '채널계정ID';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."CHANNEL_ORDER_ID" IS '채널주문번호';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."CHANNEL_ORDER_SEQ" IS '채널주문순번';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."ORDER_STATUS" IS '주문상태명';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."ORDER_STATUS_CD" IS '주문상태코드';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."BUYER_NM" IS '주문자명';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."RECEIVE_NAME" IS '수령자명';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."PRODUCT_ID" IS '상품ID';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."ITEM_ID" IS 'ITEM';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."ITEM_NAME" IS '품목명';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."SALE_CNT" IS '주문수량';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."RAW_DATA_JSON" IS '원본JSON';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."ERP_IF_YN" IS 'ERP';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."PROC_ERR_YN" IS '처리오류';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."CONFIRM_YN" IS '검토확정';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."UPDATE_DATETIME" IS '수정일시';

COMMENT ON COLUMN "BHUB_ORDER_RAW"."UPDATE_USER_ID" IS '수정자';

CREATE TABLE "BHUB_ITEM_STOCK_HIST" (
	"STOCK_HIST_ID"	VARCHAR2(30)		NOT NULL,
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"STOCK_ID"	VARCHAR2(30)		NOT NULL,
	"ITEM_ID"	VARCHAR2(30)		NOT NULL,
	"WAREHOUSE_CD"	VARCHAR2(10)		NOT NULL,
	"HIST_TP"	VARCHAR2(20)		NOT NULL,
	"CHANGE_DT"	DATE		NOT NULL,
	"CHANGE_QTY"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"BEFORE_ONHAND_QTY"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"AFTER_ONHAND_QTY"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"BEFORE_ALLOC_QTY"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"AFTER_ALLOC_QTY"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"BEFORE_AVAIL_QTY"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"AFTER_AVAIL_QTY"	NUMBER(18,0)	DEFAULT 0	NOT NULL,
	"REF_TP"	VARCHAR2(20)		NULL,
	"REF_ID"	VARCHAR2(50)		NULL,
	"CHANGE_REASON"	VARCHAR2(1000)		NULL,
	"CHANGE_USER_ID"	VARCHAR2(20)		NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."STOCK_HIST_ID" IS '재고이력ID';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."STOCK_ID" IS '재고ID';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."ITEM_ID" IS 'ITEM';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."WAREHOUSE_CD" IS '창고코드';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."HIST_TP" IS '이력유형(SYNC/ALLOC/RELEASE/ADJUST/SALE/CANCEL)';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."CHANGE_DT" IS '변경일시';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."CHANGE_QTY" IS '변경수량';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."BEFORE_ONHAND_QTY" IS '변경전현재고';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."AFTER_ONHAND_QTY" IS '변경후현재고';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."BEFORE_ALLOC_QTY" IS '변경전예약수량';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."AFTER_ALLOC_QTY" IS '변경후예약수량';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."BEFORE_AVAIL_QTY" IS '변경전가용수량';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."AFTER_AVAIL_QTY" IS '변경후가용수량';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."REF_TP" IS '참조유형(ORDER/SYNC/MANUAL/BATCH)';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."REF_ID" IS '참조ID';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."CHANGE_REASON" IS '변경사유';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."CHANGE_USER_ID" IS '변경자';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_ITEM_STOCK_HIST"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_POLICY" (
	"POLICY_CD"	VARCHAR2(50)		NOT NULL,
	"POLICY_NM"	VARCHAR2(100)		NOT NULL,
	"VALUE_TYPE_CD"	VARCHAR2(20)	DEFAULT 'STRING'	NOT NULL,
	"TARGET_CHANNEL_CD"	VARCHAR2(20)		NULL,
	"DEFAULT_VALUE"	VARCHAR2(4000)		NULL,
	"REQUIRED_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"SORT_SEQ"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_POLICY"."POLICY_CD" IS '정책코드';

COMMENT ON COLUMN "BHUB_POLICY"."POLICY_NM" IS '정책명';

COMMENT ON COLUMN "BHUB_POLICY"."VALUE_TYPE_CD" IS '값유형코드';

COMMENT ON COLUMN "BHUB_POLICY"."TARGET_CHANNEL_CD" IS '적용대상';

COMMENT ON COLUMN "BHUB_POLICY"."DEFAULT_VALUE" IS '시스템';

COMMENT ON COLUMN "BHUB_POLICY"."REQUIRED_YN" IS '필수여부';

COMMENT ON COLUMN "BHUB_POLICY"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_POLICY"."SORT_SEQ" IS '정렬순서';

COMMENT ON COLUMN "BHUB_POLICY"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_POLICY"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_POLICY"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_POLICY"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_POLICY"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_CHANNEL_POLICY" (
	"CHANNEL_CD"	VARCHAR2(20)		NOT NULL,
	"POLICY_CD"	VARCHAR2(50)		NOT NULL,
	"DEFAULT_VALUE"	VARCHAR2(4000)		NULL,
	"REQUIRED_YN"	CHAR(1)	DEFAULT '0'	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"SORT_SEQ"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY"."CHANNEL_CD" IS '채널코드';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY"."POLICY_CD" IS '정책코드';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY"."DEFAULT_VALUE" IS '채널';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY"."REQUIRED_YN" IS '채널';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY"."SORT_SEQ" IS '정렬순서';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_CHANNEL_POLICY"."UPDATE_DATETIME" IS '수정일시';

CREATE TABLE "BHUB_OPTION" (
	"CORP_CD"	VARCHAR2(10)		NOT NULL,
	"OPTION_ID"	VARCHAR2(30)		NOT NULL,
	"OPTION_CD"	VARCHAR2(50)		NOT NULL,
	"OPTION_NM"	VARCHAR2(100)		NOT NULL,
	"OPTION_TYPE"	VARCHAR2(30)	DEFAULT 'TEXT'	NOT NULL,
	"SORT_SEQ"	NUMBER(10,0)	DEFAULT 0	NOT NULL,
	"USE_YN"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"REMARK_TXT"	VARCHAR2(1000)		NULL,
	"INSERT_USER_ID"	VARCHAR2(20)		NULL,
	"INSERT_DATETIME"	DATE		NULL,
	"UPDATE_USER_ID"	VARCHAR2(20)		NULL,
	"UPDATE_DATETIME"	DATE		NULL
);

COMMENT ON COLUMN "BHUB_OPTION"."CORP_CD" IS '회사코드';

COMMENT ON COLUMN "BHUB_OPTION"."OPTION_ID" IS '옵션ID';

COMMENT ON COLUMN "BHUB_OPTION"."OPTION_CD" IS '옵션코드';

COMMENT ON COLUMN "BHUB_OPTION"."OPTION_NM" IS '옵션명';

COMMENT ON COLUMN "BHUB_OPTION"."OPTION_TYPE" IS '옵션유형';

COMMENT ON COLUMN "BHUB_OPTION"."SORT_SEQ" IS '정렬순서';

COMMENT ON COLUMN "BHUB_OPTION"."USE_YN" IS '사용여부';

COMMENT ON COLUMN "BHUB_OPTION"."REMARK_TXT" IS '비고';

COMMENT ON COLUMN "BHUB_OPTION"."INSERT_USER_ID" IS '등록자';

COMMENT ON COLUMN "BHUB_OPTION"."INSERT_DATETIME" IS '등록일시';

COMMENT ON COLUMN "BHUB_OPTION"."UPDATE_USER_ID" IS '수정자';

COMMENT ON COLUMN "BHUB_OPTION"."UPDATE_DATETIME" IS '수정일시';

ALTER TABLE "BHUB_PRODUCT_OPTION" ADD CONSTRAINT "PK_BHUB_PRODUCT_OPTION" PRIMARY KEY (
	"PRODUCT_OPTION_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_CHANNEL_POLICY_VALUE" ADD CONSTRAINT "PK_BHUB_CHANNEL_POLICY_VALUE" PRIMARY KEY (
	"CORP_CD",
	"CHANNEL_CD",
	"POLICY_CD"
);

ALTER TABLE "BHUB_CATEGORY" ADD CONSTRAINT "PK_BHUB_CATEGORY" PRIMARY KEY (
	"CATEGORY_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_ORDER" ADD CONSTRAINT "PK_BHUB_ORDER" PRIMARY KEY (
	"ORDER_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_PRODUCT_PRICE" ADD CONSTRAINT "PK_BHUB_PRODUCT_PRICE" PRIMARY KEY (
	"PRICE_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_RAW_BATCH" ADD CONSTRAINT "PK_BHUB_RAW_BATCH" PRIMARY KEY (
	"BATCH_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_ITEM_OPTION" ADD CONSTRAINT "PK_BHUB_ITEM_OPTION" PRIMARY KEY (
	"ITEM_OPTION_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_ITEM_ERP_MAP" ADD CONSTRAINT "PK_BHUB_ITEM_ERP_MAP" PRIMARY KEY (
	"MAP_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_PRODUCT_ATTR" ADD CONSTRAINT "PK_BHUB_PRODUCT_ATTR" PRIMARY KEY (
	"ATTR_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_MAPPING_REVIEW" ADD CONSTRAINT "PK_BHUB_MAPPING_REVIEW" PRIMARY KEY (
	"REVIEW_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_CHANNEL_SYNC_HIST" ADD CONSTRAINT "PK_BHUB_CHANNEL_SYNC_HIST" PRIMARY KEY (
	"SYNC_HIST_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_CHANNEL_CATEGORY" ADD CONSTRAINT "PK_BHUB_CHANNEL_CATEGORY" PRIMARY KEY (
	"CHANNEL_CATEGORY_ID"
);

ALTER TABLE "BHUB_ITEM_RAW" ADD CONSTRAINT "PK_BHUB_ITEM_RAW" PRIMARY KEY (
	"RAWITEM_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_ORDER_ITEM" ADD CONSTRAINT "PK_BHUB_ORDER_ITEM" PRIMARY KEY (
	"ORDER_PRODUCT_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_PRODUCT_HIST" ADD CONSTRAINT "PK_BHUB_PRODUCT_HIST" PRIMARY KEY (
	"CORP_CD",
	"ITEM_HIST_ID"
);

ALTER TABLE "BHUB_CHANNEL_ACCOUNT" ADD CONSTRAINT "PK_BHUB_CHANNEL_ACCOUNT" PRIMARY KEY (
	"CORP_CD",
	"CHANNEL_ACCOUNT_ID"
);

ALTER TABLE "BHUB_PRODUCT_COMPONENT" ADD CONSTRAINT "PK_BHUB_PRODUCT_COMPONENT" PRIMARY KEY (
	"COMPONENT_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_CHANNEL_ITEM" ADD CONSTRAINT "PK_BHUB_CHANNEL_ITEM" PRIMARY KEY (
	"CHANNELITEM_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_CATEGORY_CHANNEL_MAP" ADD CONSTRAINT "PK_BHUB_CATEGORY_CHANNEL_MAP" PRIMARY KEY (
	"MAP_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_OPTION_VALUE" ADD CONSTRAINT "PK_BHUB_OPTION_VALUE" PRIMARY KEY (
	"OPTION_VALUE_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_PRODUCT_COMPONENT_ITEM" ADD CONSTRAINT "PK_BHUB_PRODUCT_COMPONENT_ITEM" PRIMARY KEY (
	"COMPONENT_PRODUCT_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_ITEM_STYLE_OPTION" ADD CONSTRAINT "PK_BHUB_ITEM_STYLE_OPTION" PRIMARY KEY (
	"ITEM_STYLE_OPTION_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_CHANNEL_PRODUCT" ADD CONSTRAINT "PK_BHUB_CHANNEL_PRODUCT" PRIMARY KEY (
	"CHANNEL_PRODUCT_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_PRODUCT_MATCH" ADD CONSTRAINT "PK_BHUB_PRODUCT_MATCH" PRIMARY KEY (
	"MATCH_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_PRODUCT_RAW" ADD CONSTRAINT "PK_BHUB_PRODUCT_RAW" PRIMARY KEY (
	"RAW_PRODUCT_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_PRODUCT_IMAGE" ADD CONSTRAINT "PK_BHUB_PRODUCT_IMAGE" PRIMARY KEY (
	"IMAGE_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_CHANNEL_SEND_BATCH" ADD CONSTRAINT "PK_BHUB_CHANNEL_SEND_BATCH" PRIMARY KEY (
	"SEND_BATCH_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_CHANNEL_SEND_HIST" ADD CONSTRAINT "PK_BHUB_CHANNEL_SEND_HIST" PRIMARY KEY (
	"SEND_HIST_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_ITEM" ADD CONSTRAINT "PK_BHUB_ITEM" PRIMARY KEY (
	"ITEM_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_ORDER_SEND" ADD CONSTRAINT "PK_BHUB_ORDER_SEND" PRIMARY KEY (
	"ORDER_SEND_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_PRODUCT_ITEM" ADD CONSTRAINT "PK_BHUB_PRODUCT_ITEM" PRIMARY KEY (
	"PRODUCT_ITEM_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_PRODUCT" ADD CONSTRAINT "PK_BHUB_PRODUCT" PRIMARY KEY (
	"CORP_CD",
	"PRODUCT_ID"
);

ALTER TABLE "BHUB_ITEM_STOCK" ADD CONSTRAINT "PK_BHUB_ITEM_STOCK" PRIMARY KEY (
	"STOCK_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_CHANNEL" ADD CONSTRAINT "PK_BHUB_CHANNEL" PRIMARY KEY (
	"CHANNEL_CD"
);

ALTER TABLE "BHUB_ITEM_STYLE" ADD CONSTRAINT "PK_BHUB_ITEM_STYLE" PRIMARY KEY (
	"CORP_CD",
	"ITEM_STYLE_ID"
);

ALTER TABLE "BHUB_PRODUCT_SEND" ADD CONSTRAINT "PK_BHUB_PRODUCT_SEND" PRIMARY KEY (
	"SEND_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_ITEM_STYLE_OPTION_VALUE" ADD CONSTRAINT "PK_BHUB_ITEM_STYLE_OPTION_VALUE" PRIMARY KEY (
	"ITEM_STYLE_OPTION_VALUE_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_ORDER_RAW" ADD CONSTRAINT "PK_BHUB_ORDER_RAW" PRIMARY KEY (
	"RAW_ORDER_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_ITEM_STOCK_HIST" ADD CONSTRAINT "PK_BHUB_ITEM_STOCK_HIST" PRIMARY KEY (
	"STOCK_HIST_ID",
	"CORP_CD"
);

ALTER TABLE "BHUB_POLICY" ADD CONSTRAINT "PK_BHUB_POLICY" PRIMARY KEY (
	"POLICY_CD"
);

ALTER TABLE "BHUB_CHANNEL_POLICY" ADD CONSTRAINT "PK_BHUB_CHANNEL_POLICY" PRIMARY KEY (
	"CHANNEL_CD",
	"POLICY_CD"
);

ALTER TABLE "BHUB_OPTION" ADD CONSTRAINT "PK_BHUB_OPTION" PRIMARY KEY (
	"CORP_CD",
	"OPTION_ID"
);

ALTER TABLE "BHUB_PRODUCT_OPTION" ADD CONSTRAINT "FK_BHUB_OPTION_TO_BHUB_PRODUCT_OPTION_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_OPTION" (
	"CORP_CD"
);

ALTER TABLE "BHUB_CHANNEL_POLICY_VALUE" ADD CONSTRAINT "FK_BHUB_CHANNEL_POLICY_TO_BHUB_CHANNEL_POLICY_VALUE_1" FOREIGN KEY (
	"CHANNEL_CD"
)
REFERENCES "BHUB_CHANNEL_POLICY" (
	"CHANNEL_CD"
);

ALTER TABLE "BHUB_CHANNEL_POLICY_VALUE" ADD CONSTRAINT "FK_BHUB_CHANNEL_POLICY_TO_BHUB_CHANNEL_POLICY_VALUE_2" FOREIGN KEY (
	"POLICY_CD"
)
REFERENCES "BHUB_CHANNEL_POLICY" (
	"POLICY_CD"
);

ALTER TABLE "BHUB_CATEGORY" ADD CONSTRAINT "FK_BHUB_CATEGORY_TO_BHUB_CATEGORY_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_CATEGORY" (
	"CORP_CD"
);

ALTER TABLE "BHUB_ORDER" ADD CONSTRAINT "FK_BHUB_CHANNEL_ACCOUNT_TO_BHUB_ORDER_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_CHANNEL_ACCOUNT" (
	"CORP_CD"
);

ALTER TABLE "BHUB_PRODUCT_PRICE" ADD CONSTRAINT "FK_BHUB_PRODUCT_TO_BHUB_PRODUCT_PRICE_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_PRODUCT" (
	"CORP_CD"
);

ALTER TABLE "BHUB_RAW_BATCH" ADD CONSTRAINT "FK_BHUB_CHANNEL_ACCOUNT_TO_BHUB_RAW_BATCH_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_CHANNEL_ACCOUNT" (
	"CORP_CD"
);

ALTER TABLE "BHUB_ITEM_OPTION" ADD CONSTRAINT "FK_BHUB_OPTION_VALUE_TO_BHUB_ITEM_OPTION_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_OPTION_VALUE" (
	"CORP_CD"
);

ALTER TABLE "BHUB_ITEM_ERP_MAP" ADD CONSTRAINT "FK_BHUB_ITEM_TO_BHUB_ITEM_ERP_MAP_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_ITEM" (
	"CORP_CD"
);

ALTER TABLE "BHUB_PRODUCT_ATTR" ADD CONSTRAINT "FK_BHUB_PRODUCT_TO_BHUB_PRODUCT_ATTR_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_PRODUCT" (
	"CORP_CD"
);

ALTER TABLE "BHUB_MAPPING_REVIEW" ADD CONSTRAINT "FK_BHUB_ITEM_RAW_TO_BHUB_MAPPING_REVIEW_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_ITEM_RAW" (
	"CORP_CD"
);

ALTER TABLE "BHUB_CHANNEL_SYNC_HIST" ADD CONSTRAINT "FK_BHUB_CHANNEL_ACCOUNT_TO_BHUB_CHANNEL_SYNC_HIST_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_CHANNEL_ACCOUNT" (
	"CORP_CD"
);

ALTER TABLE "BHUB_ITEM_RAW" ADD CONSTRAINT "FK_BHUB_PRODUCT_RAW_TO_BHUB_ITEM_RAW_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_PRODUCT_RAW" (
	"CORP_CD"
);

ALTER TABLE "BHUB_ORDER_ITEM" ADD CONSTRAINT "FK_BHUB_ORDER_TO_BHUB_ORDER_ITEM_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_ORDER" (
	"CORP_CD"
);

ALTER TABLE "BHUB_PRODUCT_COMPONENT" ADD CONSTRAINT "FK_BHUB_PRODUCT_TO_BHUB_PRODUCT_COMPONENT_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_PRODUCT" (
	"CORP_CD"
);

ALTER TABLE "BHUB_CHANNEL_ITEM" ADD CONSTRAINT "FK_BHUB_ITEM_TO_BHUB_CHANNEL_ITEM_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_ITEM" (
	"CORP_CD"
);

ALTER TABLE "BHUB_CATEGORY_CHANNEL_MAP" ADD CONSTRAINT "FK_BHUB_CATEGORY_TO_BHUB_CATEGORY_CHANNEL_MAP_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_CATEGORY" (
	"CORP_CD"
);

ALTER TABLE "BHUB_OPTION_VALUE" ADD CONSTRAINT "FK_BHUB_OPTION_TO_BHUB_OPTION_VALUE_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_OPTION" (
	"CORP_CD"
);

ALTER TABLE "BHUB_PRODUCT_COMPONENT_ITEM" ADD CONSTRAINT "FK_BHUB_PRODUCT_COMPONENT_TO_BHUB_PRODUCT_COMPONENT_ITEM_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_PRODUCT_COMPONENT" (
	"CORP_CD"
);

ALTER TABLE "BHUB_ITEM_STYLE_OPTION" ADD CONSTRAINT "FK_BHUB_OPTION_TO_BHUB_ITEM_STYLE_OPTION_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_OPTION" (
	"CORP_CD"
);

ALTER TABLE "BHUB_CHANNEL_PRODUCT" ADD CONSTRAINT "FK_BHUB_PRODUCT_TO_BHUB_CHANNEL_PRODUCT_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_PRODUCT" (
	"CORP_CD"
);

ALTER TABLE "BHUB_PRODUCT_MATCH" ADD CONSTRAINT "FK_BHUB_ITEM_RAW_TO_BHUB_PRODUCT_MATCH_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_ITEM_RAW" (
	"CORP_CD"
);

ALTER TABLE "BHUB_PRODUCT_RAW" ADD CONSTRAINT "FK_BHUB_RAW_BATCH_TO_BHUB_PRODUCT_RAW_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_RAW_BATCH" (
	"CORP_CD"
);

ALTER TABLE "BHUB_PRODUCT_IMAGE" ADD CONSTRAINT "FK_BHUB_PRODUCT_TO_BHUB_PRODUCT_IMAGE_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_PRODUCT" (
	"CORP_CD"
);

ALTER TABLE "BHUB_CHANNEL_SEND_BATCH" ADD CONSTRAINT "FK_BHUB_CHANNEL_ACCOUNT_TO_BHUB_CHANNEL_SEND_BATCH_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_CHANNEL_ACCOUNT" (
	"CORP_CD"
);

ALTER TABLE "BHUB_CHANNEL_SEND_HIST" ADD CONSTRAINT "FK_BHUB_CHANNEL_SEND_BATCH_TO_BHUB_CHANNEL_SEND_HIST_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_CHANNEL_SEND_BATCH" (
	"CORP_CD"
);

ALTER TABLE "BHUB_ITEM" ADD CONSTRAINT "FK_BHUB_PRODUCT_TO_BHUB_ITEM_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_PRODUCT" (
	"CORP_CD"
);

ALTER TABLE "BHUB_ORDER_SEND" ADD CONSTRAINT "FK_BHUB_ORDER_TO_BHUB_ORDER_SEND_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_ORDER" (
	"CORP_CD"
);

ALTER TABLE "BHUB_ITEM_STOCK" ADD CONSTRAINT "FK_BHUB_ITEM_TO_BHUB_ITEM_STOCK_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_ITEM" (
	"CORP_CD"
);

ALTER TABLE "BHUB_PRODUCT_SEND" ADD CONSTRAINT "FK_BHUB_CHANNEL_SEND_BATCH_TO_BHUB_PRODUCT_SEND_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_CHANNEL_SEND_BATCH" (
	"CORP_CD"
);

ALTER TABLE "BHUB_ITEM_STYLE_OPTION_VALUE" ADD CONSTRAINT "FK_BHUB_OPTION_VALUE_TO_BHUB_ITEM_STYLE_OPTION_VALUE_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_OPTION_VALUE" (
	"CORP_CD"
);

ALTER TABLE "BHUB_ORDER_RAW" ADD CONSTRAINT "FK_BHUB_RAW_BATCH_TO_BHUB_ORDER_RAW_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_RAW_BATCH" (
	"CORP_CD"
);

ALTER TABLE "BHUB_ITEM_STOCK_HIST" ADD CONSTRAINT "FK_BHUB_ITEM_STOCK_TO_BHUB_ITEM_STOCK_HIST_1" FOREIGN KEY (
	"CORP_CD"
)
REFERENCES "BHUB_ITEM_STOCK" (
	"CORP_CD"
);

ALTER TABLE "BHUB_CHANNEL_POLICY" ADD CONSTRAINT "FK_BHUB_CHANNEL_TO_BHUB_CHANNEL_POLICY_1" FOREIGN KEY (
	"CHANNEL_CD"
)
REFERENCES "BHUB_CHANNEL" (
	"CHANNEL_CD"
);

ALTER TABLE "BHUB_CHANNEL_POLICY" ADD CONSTRAINT "FK_BHUB_POLICY_TO_BHUB_CHANNEL_POLICY_1" FOREIGN KEY (
	"POLICY_CD"
)
REFERENCES "BHUB_POLICY" (
	"POLICY_CD"
);

