export type WchanOrder = {
  [key: string]: unknown;
  rdmg_code: string;
  rdmg_index: number;
  rdmg_order_date: string;
  rdmg_order_status: number;
  rdmg_price: number;
  rdmg_delivery_cost: number;
  rdmg_delivery_type: number;
  rdmg_delivery_on: string;
  rdmg_buy_amount: number;
  rdmg_contents: string;
  rdmg_payment_composition: string;
  gdmg_code: string;
  gdmg_goods_name: string;
  gdmg_mange_code: string;
  gdmg_support_price: number;
  gdmg_sale_channel: number;
  wmng_name: string;
  mdtf_reg_name: string;
  mdtf_ceo_name: string;
  mdtf_phone: string;
  sellerId: string;
  odermbsd_id: string;
  lmmf_idx: string;
  lmmf_name: string;
  mbgr_hp: string;
  rddr_name: string;
  lastStatusDate: string;
  gmgg_url: string;
  gmgg_name: string;
  gmgg_file_format: string;
};
